all:
	g++ answer.cpp -o answer.cppx
	./answer.cppx
	./answer.js
	./answer.rb
	./answer.py
	./answer.sh
	rm *x
cpp:
	g++ answer.cpp -o answer.cppx
clean:
	if [ -a *~ ] ; \
	then \
		rm *~ ;\
	fi;
	if [ -a *x ] ; \
	then \
		rm *x ;\
	fi;
	if [ -a *# ] ; \
	then \
		rm *# ;\
	fi;
	clear
