all:
	g++ answer.cpp -o answer.cppx
	javac answer.java
	./answer.cppx
	./answer.js
	./answer.rb
	./answer.py
	./answer.sh
	./answer.r
	java answer
	rm *x
	rm *class
cpp:
	g++ answer.cpp -o answer.cppx
java:
	javac answer.java
clean:
	if [ -a *~ ] ; \
	then \
		rm *~ ;\
	fi;
	if [ -a *x ] ; \
	then \
		rm *x ;\
	fi;
	if [ -a *# ] ; \
	then \
		rm *# ;\
	fi;
	if [ -a *class ] ; \
	then \
		rm *class ;\
	fi;
	clear
